Frontify/guideline-blocks

packages/storybook-block/src/StorybookBlock.spec.ct.tsx, packages/storybook-block/src/StorybookBlock.tsx, packages/storybook-block/src/utilities.ts
https://app.clickup.com/t/2qg37ep
=> fix(StorybookBlock): decode urls

packages/shared/src/settings/border.ts, packages/shared/src/settings/borderRadius.ts, packages/storybook-block/src/StorybookBlock.spec.ct.tsx, packages/storybook-block/src/StorybookBlock.tsx, packages/storybook-block/src/settings.ts, packages/storybook-block/src/types.ts
ticket: https://app.clickup.com/t/2t7u1we
=> feat(Storybook Block):Multiple minor fixes

packages/storybook-block/src/StorybookBlock.spec.ct.tsx, packages/storybook-block/src/StorybookBlock.tsx, packages/storybook-block/src/settings.ts
handle deletion ticket: https://app.clickup.com/t/2u0eb89
placeholder & error msg ticket: https://app.clickup.com/t/2vkwt1m
=> feat(StorybookBlock): fix deletion handling, url placeholder and input validation

packages/storybook-block/src/settings.ts
ticket: https://app.clickup.com/t/2vkwt1m
=> feat(StorybookBlock): remove e.g. from url placeholder

packages/block-settings/types/blocks/base.ts, packages/block-settings/types/blocks/checklist.ts, packages/block-settings/types/bundle.ts, packages/shared/src/helpers/settings/appendUnit.spec.ts, packages/shared/src/helpers/settings/presetCustomValue.spec.ts, packages/sketchfab-block/src/helpers/settings.spec.ct.ts
This PR implements the `ValueOrPromisedValue` type and adds `getAppBridge` to the `Bundle`
=> feat: add ValueOrPromisedValue type

packages/quote-block/src/QuoteBlock.tsx, packages/quote-block/src/settings.ts, packages/quote-block/src/settings.tsx, packages/quote-block/src/types.ts
ticket: https://app.clickup.com/t/2ry3j82
six icons are directly passed within the settings file, as they are not available in fondue atm. Will be replaced as soon as new ones are available (https://app.clickup.com/t/2y3u4nk)
=> feat(QuoteBlock): simplify, fix & read icons

packages/divider-block/src/settings.ts
Ticket: https://app.clickup.com/t/2t7u1ww
=> fix(DividerBlock): adjust labels for divider style

packages/block-settings/types/blocks/base.ts, packages/divider-block/src/settings.ts, pnpm-lock.yaml
This PR adds a conditional tooltip text for the height setting.
Ticket: https://app.clickup.com/t/2t7u1ww
=> feat(DividerBlock): conditional tooltip text

packages/color-kit-block/src/Color.tsx, packages/color-kit-block/src/ColorKitBlock.tsx, packages/color-kit-block/src/EmptyView.tsx, packages/color-kit-block/src/Palette.spec.ct.tsx, packages/color-kit-block/src/Palette.tsx, packages/color-kit-block/src/settings.ts
Based on the comments from here: https://app.clickup.com/t/2wmf7nk
=> feat(ColorKitBlock): design review changes

packages/code-snippet-block/src/components/CodeMirrorEditor/codeMirrorEditor.css, packages/code-snippet-block/src/settings.ts, packages/shared/src/settings/borderRadius.ts, packages/shared/src/settings/borderRadiusExtended.ts, packages/shared/src/settings/margin.ts
Tasks here: https://app.clickup.com/t/2ymz8my
=> feat:(CodeSnippetBlock): design review changes

packages/colors-block/src/ColorsBlock.spec.ct.tsx, packages/colors-block/src/components/ColorName.tsx, packages/colors-block/src/components/ColorPickerFlyout.tsx, packages/colors-block/src/components/ColorSpaceValue.tsx, packages/colors-block/src/components/DropZone.spec.ct.tsx, packages/colors-block/src/components/TooltipContent.spec.ct.tsx, packages/colors-block/src/components/TooltipContent.tsx, packages/colors-block/src/components/cards/CardsItem.tsx, packages/colors-block/src/components/cards/CardsItemAdd.tsx, packages/colors-block/src/components/drops/DropsItem.spec.ct.tsx, packages/colors-block/src/components/drops/DropsItem.tsx, packages/colors-block/src/components/drops/DropsItemAdd.tsx, packages/colors-block/src/components/list/ListItem.tsx, packages/colors-block/src/components/list/ListItemAdd.tsx, packages/colors-block/src/types.ts, packages/colors-block/tailwind.config.js
As requested in: https://app.clickup.com/t/2y9jphr.
Note: currently missing ~~two~~ ~~one~~ zero fixes from the ticket 🥳
=> feat(ColorsBlock): design review changes

packages/quote-block/src/Quotations.tsx, packages/quote-block/src/QuoteBlock.spec.ct.tsx, packages/quote-block/src/QuoteBlock.tsx, packages/quote-block/src/QuoteBlockIcon.tsx, packages/quote-block/src/settings.tsx, packages/quote-block/src/types.ts, packages/quote-block/src/utilities.tsx
This PR adds an option to add custom icons:
https://app.clickup.com/t/2y40cee
=> feat(quote-block): Add option to add custom icons

packages/quote-block/manifest.json
Add setting fields `authorName` & `content` to be indexed
=> feat(QuoteBlock): add searchFields

packages/quote-block/src/QuoteBlock.tsx, packages/quote-block/src/settings.tsx, packages/quote-block/src/types.ts
Nitpicky, but better do it before doing the migration :)
=> fix(QuoteBlock): camel case for accentLineColor

packages/colors-block/src/components/ColorPickerFlyout.spec.ct.tsx, packages/colors-block/src/components/ColorPickerFlyout.tsx, packages/colors-block/src/components/list/ListItem.tsx
Resolved issues in the PR:
- fixing the css issue of items not being aligned on beta
- allow dragging over the color picker flyout
=> fix(ColorsBlock): Design review fixes

packages/storybook-block/src/StorybookBlock.spec.ct.tsx, packages/storybook-block/src/StorybookBlock.tsx
Task: https://app.clickup.com/t/2x775mp
=> feat: lazy load storybook block iframe

packages/callout-block/manifest.json, packages/personal-note-block/manifest.json, packages/quote-block/manifest.json
Add `searchFields` to Callout, Quote & Personal Note
=> feat: add searchFields to Callout, Quote & Personal Note blocks

packages/personal-note-block/src/components/NoteHeader.tsx
Check if date actually is valid, output string otherwise.
=> fix(PersonalNoteBlock): check for valid date

packages/quote-block/src/QuoteBlock.spec.ct.tsx, packages/quote-block/src/QuoteBlock.tsx, packages/quote-block/src/QuoteBlockIcon.tsx, packages/quote-block/src/settings.tsx, packages/quote-block/src/types.ts
As discussed with Martin Kovacovsky & @triggertoo.
Design: https://www.figma.com/file/pYt8ECuB6Sc63cVtpKiDgf/Blocks---Updated-Q4-2022?node-id=485%3A130841
=> feat(QuoteBlock): new default values & use Guideline Tokens for icon color

packages/block-settings/types/blocks/choices.ts
=> feat: add promise on `choices`

packages/quote-block/src/QuoteBlock.tsx, packages/quote-block/src/settings.tsx
=> fix(QuoteBlock): show placeholder only in edit mode

package-lock.json, packages/figma-block/src/FigmaBlock.tsx, packages/figma-block/src/ImageStage.tsx, packages/figma-block/src/components/ImageStage.ts, packages/figma-block/src/helpers/index.ts, packages/figma-block/src/helpers/mapCommonStyle.ts, packages/figma-block/src/settings.ts, packages/figma-block/src/types.ts, packages/figma-block/src/useImageStage.ts
Improvements:
- Min height changed to 50
- Responsive on mobile
- Added advanced border options
- Live mode also responds to style and height mods
=> feat(FigmaBlock): various improvements

packages/code-snippet-block/src/CodeSnippetBlock.tsx, packages/code-snippet-block/src/headerThemes.ts, packages/code-snippet-block/src/settings.ts, packages/code-snippet-block/src/types.ts
https://app.clickup.com/t/377q8hp
- Add themes to header
- Only show placeholder in edit mode
=> feat(CodeSnippetBlock): some improvements

packages/figma-block/src/FigmaBlock.tsx, packages/figma-block/src/ImageStage.tsx, packages/figma-block/src/ReferenceErrorMessage.tsx, packages/figma-block/src/components/ContainerOperator/VectorContainerOperator.ts, packages/figma-block/src/settings.ts, packages/figma-block/src/tests/BlockContainerStub.tsx, packages/figma-block/src/types.ts, packages/figma-block/src/useImageStage.ts
In addition:
- Add Corner Radius
- Resize image on Full Screen
- Small styling changes
=> feat(FigmaBlock): show error message on reference

packages/text-block/src/settings.ts
Based on the review on this ticket: https://app.clickup.com/t/2ry3jbw
=> feat(TextBlock): fix gutter settings and remove main dropdown in settings

packages/callout-block/package.json, packages/quote-block/package.json, packages/shared/src/helpers/mapToGuidelineDesignTokens.ts, pnpm-lock.yaml
Also revert Fondue in Callout and Quote block, because the RTE is broken in the newest version.
- Callout block -> already uploaded a new version of the block as a hotfix (v17)
- Quote block -> need to upload a new version to fix this: https://app.clickup.com/t/2523021/TASK-5685
=> fix(shared): check for `null` values

packages/shared/src/helpers/font.spec.ts, packages/shared/src/helpers/font.ts, packages/shared/src/helpers/mapToGuidelineDesignTokens.spec.ts, packages/shared/src/helpers/mapToGuidelineDesignTokens.ts
ticket: https://app.clickup.com/t/86775v47c
=> feat(shared): adapt useGuidelineDesignTokens to use main and system font

packages/dos-donts-block/package.json, packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/DosDontsBlock.spec.ct.tsx, packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/components/BlockEditButton.tsx, packages/dos-donts-block/src/components/IconComponent.tsx, packages/dos-donts-block/src/components/ImageComponent.tsx, packages/dos-donts-block/src/components/ItemToolbar.tsx, packages/dos-donts-block/src/settings.ts, packages/dos-donts-block/src/types.ts, packages/dos-donts-block/tailwind.config.js, pnpm-lock.yaml, tailwind.config.js
Do & Don't V2.
Figma spec:
https://www.figma.com/file/pYt8ECuB6Sc63cVtpKiDgf/Blocks---Updated-Q4-2022?node-id=1097%3A266625&t=sbLqYEdhwDImFeo3-0
=> feat(DoDontBlock): update do dont block

packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/DosDontsBlock.spec.ct.tsx, packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/components/BlockEditButton.tsx, packages/dos-donts-block/src/components/ItemToolbar.tsx, packages/dos-donts-block/src/settings.ts, packages/shared/src/utilities/color/index.ts, packages/shared/src/utilities/color/toColorObject.spec.ts, packages/shared/src/utilities/color/toColorObject.ts
- Add tooltips
- Add padding to the purple outline
- Set correct font
- Change upload button outline to solid
- Draw accent colors for Do & Dont color
- Some copy changes
=> feat(DoDontBlock): add several QOL improvements

packages/brand-positioning-block/.eslintrc.js, packages/brand-positioning-block/.gitignore, packages/brand-positioning-block/.prettierrc, packages/brand-positioning-block/README.md, packages/brand-positioning-block/manifest.json, packages/brand-positioning-block/package.json, packages/brand-positioning-block/postcss.config.js, packages/brand-positioning-block/src/BrandPositioningBlock.spec.ct.tsx, packages/brand-positioning-block/src/BrandPositioningBlock.tsx, packages/brand-positioning-block/src/index.ts, packages/brand-positioning-block/src/settings.ts, packages/brand-positioning-block/src/types.ts, packages/brand-positioning-block/tailwind.config.js, packages/brand-positioning-block/tsconfig.json, pnpm-lock.yaml
Skeleton for Brand positioning block.
=> feat(BrandPositioning): add skeleton

packages/dos-donts-block/package.json, packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/DosDontsBlock.spec.ct.tsx, packages/text-block/package.json, packages/text-block/src/getPlugins.tsx, pnpm-lock.yaml
- Update fondue in text block
- Add init plugin to RTE in text block
- Update fondue in do & dont block
- Implement html view mode in do & dont block
=> feat(Text & DoDont): implement html view mode & update fondue

packages/code-snippet-block/src/CodeSnippetBlock.tsx
Next Fondue version removed `iconsMap`
=> refactor: remove `iconsMap`

packages/callout-block/package.json, packages/callout-block/src/CalloutBlock.spec.ct.tsx, packages/callout-block/src/CalloutBlock.tsx, packages/dos-donts-block/src/DoDontItem.tsx, packages/text-block/src/TextBlock.tsx, pnpm-lock.yaml
- Display html in view mode of block, instead of the RTE
- Update fondue
=> feat(CalloutBlock): implement html-view-mode & update fondue

packages/callout-block/package.json, packages/callout-block/src/CalloutBlock.tsx, pnpm-lock.yaml
- Make HTML view full width, in order to get text alignment to work correctly
- Update fondue, which includes a fix for the html serializer
=> fix(CalloutBlock): html view mode

examples/asset-upload/package.json, package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/code-snippet-block/src/CodeSnippetBlock.tsx, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/image-block/package.json, packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/ImageCaption.tsx, packages/image-block/src/components/helpers.ts, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/shared/readme.md, packages/shared/src/components/Attachments/Attachments.tsx, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, packages/text-block/src/getPlugins.tsx, pnpm-lock.yaml
Ticket: https://app.clickup.com/t/8677a21bv
=> feat(imageBlock): caption

packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/components/ImageComponent.tsx, packages/dos-donts-block/src/types.ts, packages/shared/src/components/BlockItemWrapper/BlockItemWrapper.tsx
1. RTE link chooser was behind elements => changed ZIndex behaviour.
2. There was too much space under h3.
=> fix(DoDontBlock): zindex and height issues

packages/shared/package.json, packages/shared/src/components/Attachments/AttachmentItem.tsx, packages/shared/src/components/Attachments/Attachments.tsx, packages/shared/src/components/Attachments/types.ts, packages/shared/src/components/DownloadButton/DownloadButton.tsx, pnpm-lock.yaml
Small UX Improvments for the attachments component 
They are coming from the review of the audio block [task](https://app.clickup.com/t/ndbnjd)
=> feat(shared): attachment improvements

packages/audio-block/package.json, packages/audio-block/src/AudioBlock.tsx, packages/audio-block/src/components/ItemToolbar.tsx, packages/audio-block/src/types.ts, pnpm-lock.yaml
Hopefully the last round of changes for the audio block... 
Improved UX (misunderstood Martin on the part about when the outline with the toolbar should shine, outline in Edit Mode and just on hover or focus)
Improved Accessibility Toolbar is now "fully" accessible by keyboard
=> feat: audio block accessibility improvements

packages/audio-block/src/AudioBlock.tsx
This was mentioned in the review of the block 
[Task](https://app.clickup.com/t/ndbnjd)
=> feat: audio block remove delete from toolbarFlyoutItems

packages/asset-kit-block/src/AssetKitBlock.spec.ct.tsx, packages/asset-kit-block/src/components/ThumbnailItem.tsx, packages/asset-kit-block/src/settings.ts
[Task](https://app.clickup.com/t/8677h7hew)
- Remove delete from the toolbarFlyoutItems
- Thumbnail Border Radius should be independent from the thumbnail border itself
=> feat: Asset Kit review adjustments

packages/audio-block/src/AudioBlock.tsx, packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/ImageCaption.tsx, packages/image-block/src/components/UploadPlaceholder.tsx, packages/image-block/src/components/helpers.ts, packages/image-block/src/settings.ts
implements: https://app.clickup.com/t/8677fcy7n
fixes:
* only image formats allowed (error mgs in drop)
* added selected Asset id
* audio block: allow capital audio formats & active audio in assetChooser
* use convertToRteValue()
=> feat(imageBlock): use BlockItemWrapper and convertToRteValue

packages/asset-kit-block/src/AssetKitBlock.spec.ct.tsx, packages/asset-kit-block/src/settings.ts
A small bug, the corner radius for the block should be independent from the border setting of the block (same as for the thumbnail)
=> feat: asset kit review

packages/audio-block/src/AudioBlock.tsx, packages/shared/src/components/RichTextEditor/RichTextEditor.spec.ct.tsx, packages/shared/src/components/RichTextEditor/RichTextEditor.tsx, packages/shared/src/components/RichTextEditor/types.ts, packages/text-block/src/TextBlock.tsx
Changed the handling so its more flexible and could be used everywhere 😄
=> refactor(shared): RichTextEditor flexibility

packages/code-snippet-block/package.json, packages/gradient-block/package.json, packages/gradient-block/src/GradientBlock.spec.ct.tsx, packages/gradient-block/src/GradientBlock.tsx, packages/gradient-block/src/components/AddColorButton.tsx, packages/gradient-block/src/components/ColorFlyout.tsx, packages/gradient-block/src/components/CssValueDisplay.tsx, pnpm-lock.yaml
1. Add form control to flyout
2. Force gradient points to be between 0 and 100
3. Change some labels
=> fix(GradientBlock): fix review issues

packages/text-block/manifest.json
add i18nFields so the translation bar is shown again
[Checkout](https://product.frontify.com/document/11/ar/new-blocks-1#/new-content-blocks/text-block-1)
=> feat(textBlock): add i18nFields

packages/gradient-block/src/GradientBlock.spec.ct.tsx, packages/gradient-block/src/components/ColorFlyout.tsx, packages/gradient-block/src/components/SquareBadge.tsx, packages/gradient-block/src/components/SquareBadgesRow.tsx, packages/gradient-block/src/helpers/SquareBadgeHelper.ts
[Task](https://app.clickup.com/t/8677uqnq0)
UX Review finding which was caused problems if multiple color had the same position.
=> fix(gradient-block): Position Uniqueness

packages/animation-curve-block/manifest.json, packages/asset-kit-block/manifest.json, packages/audio-block/manifest.json, packages/brand-positioning-block/manifest.json, packages/callout-block/manifest.json, packages/checklist-block/manifest.json, packages/code-snippet-block/manifest.json, packages/compare-slider-block/manifest.json, packages/dos-donts-block/manifest.json, packages/example/manifest.json, packages/image-block/manifest.json, packages/personal-note-block/manifest.json, packages/quote-block/manifest.json, packages/text-block/manifest.json
[Task](https://app.clickup.com/t/8677vgt82)
checked all blocks and added missing fields to the `manifest.json`
=> feat: added i18nFields and searchFields

packages/animation-curve-block/src/AnimationCurveBlock.spec.ct.tsx, packages/animation-curve-block/src/AnimationCurveBlock.tsx, packages/animation-curve-block/src/components/AnimationCanvas.tsx, packages/animation-curve-block/src/components/AnimationCurveFlyout.tsx, packages/animation-curve-block/src/components/Card.tsx, packages/animation-curve-block/src/settings.ts, packages/animation-curve-block/src/types.ts, packages/shared/src/components/CssValueDisplay/CssValueDisplay.tsx, packages/shared/src/settings/gutter.ts, packages/shared/src/settings/index.ts, packages/shared/src/settings/types.ts, packages/text-block/src/settings.ts, packages/text-block/src/types.ts
[Task](https://app.clickup.com/t/865c7g96v)
Shared:
- added getGutterSettings (used within Text-Block and Animation-Curve-Block)
=> feat(animationCurveBlock): second round of ux fixes 

packages/thumbnail-grid-block/.eslintrc.js, packages/thumbnail-grid-block/.gitignore, packages/thumbnail-grid-block/.prettierrc, packages/thumbnail-grid-block/README.md, packages/thumbnail-grid-block/manifest.json, packages/thumbnail-grid-block/package.json, packages/thumbnail-grid-block/postcss.config.js, packages/thumbnail-grid-block/src/ThumbnailGridBlock.spec.ct.tsx, packages/thumbnail-grid-block/src/ThumbnailGridBlock.tsx, packages/thumbnail-grid-block/src/components/Grid/Grid.tsx, packages/thumbnail-grid-block/src/components/Grid/index.ts, packages/thumbnail-grid-block/src/components/Thumbnail/Image.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/ImageWrapper.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Item.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/RichTextEditors.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/UploadPlaceholder.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/index.ts, packages/thumbnail-grid-block/src/components/index.ts, packages/thumbnail-grid-block/src/configuration/index.ts, packages/thumbnail-grid-block/src/helper/index.ts, packages/thumbnail-grid-block/src/helper/plugins.ts, packages/thumbnail-grid-block/src/helper/stylingHelper.ts, packages/thumbnail-grid-block/src/index.ts, packages/thumbnail-grid-block/src/settings.ts, packages/thumbnail-grid-block/src/types.ts, packages/thumbnail-grid-block/tailwind.config.js, packages/thumbnail-grid-block/tsconfig.json, pnpm-lock.yaml
[ticket](https://app.clickup.com/t/8677h51hv)
[Design](https://www.figma.com/file/KNDDzTo1hzVr1tt5NXUnUg/New-Content-Block---Thumbnail-grid?node-id=1832-329781&t=sIuGqMHtvCLR6jA1-0)
(button: apply textstyles will be evaluate in a separate ticket)
=> feat: add Thumbnail Grid Block

packages/shared/src/components/RichTextEditor/RichTextEditor.spec.ct.tsx, packages/shared/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/InsertButtonModal/useInsertModal.ts, packages/shared/src/components/RichTextEditor/plugins/ButtonPlugin/createButtonPlugin.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/InsertLinkModal/useInsertModal.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/index.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/utils/index.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/utils/regex.spec.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/utils/regex.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/utils/url.spec.ts, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/utils/url.ts
1. Prepend URL with https:// if not exists.
2. Allow adding URLs that begin with /document/....
=> feat(RTE): allow document paths

packages/glyphs-block/src/GlpyhsBlock.spec.ct.tsx, packages/glyphs-block/src/GlyphsBlock.tsx, packages/glyphs-block/src/helpers.ts, packages/glyphs-block/src/settings.ts, packages/glyphs-block/src/types.ts
Fixes for design review: https://app.clickup.com/t/863ghy2bx
=> feat(GlyphsBlock): adjust border, radius & settings

packages/shared/src/components/BlockItemWrapper/BlockItemWrapper.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Item.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/RichTextEditors.tsx
ticket: https://app.clickup.com/t/8677h51hv
* fix flyout placement
* rename some labels
* improve RTE performance by only using updateValueOnChange on the placeholder
* hide toolbar in viewmode
=> feat(thumbnailGridBlock): minor design changes

packages/glyphs-block/src/GlpyhsBlock.spec.ct.tsx, packages/glyphs-block/src/GlyphsBlock.tsx, packages/glyphs-block/src/settings.ts
- Remove logic to automatically add lowercase for uppercase letters
- Fix border radius logic
- Change default value
=> feat(GlyphBlock): remove upper/lowercase logic, fix border radius logic

packages/asset-kit-block/src/AssetKitBlock.tsx
Add missing hover styles for the download button. Ticket: https://app.clickup.com/t/86782dgy4
=> feat(AssetKitBlock): add hover styles for button

packages/animation-curve-block/src/AnimationCurveBlock.spec.ct.tsx, packages/thumbnail-grid-block/src/ThumbnailGridBlock.spec.ct.tsx
See: https://docs.cypress.io/guides/component-testing/react/api
=> fix(AnimationCurve & ThumbnailGrid): use cypress/react18

packages/shared/src/components/RichTextEditor/plugins/TextStylePlugins/quotePlugin.tsx
[Task](https://app.clickup.com/t/867835tgh)
=> fix(shared): QuotePlugin

packages/audio-block/src/AudioBlock.tsx, packages/audio-block/src/components/AudioPlayer.tsx, packages/audio-block/src/components/UploadPlaceholder.tsx
https://app.clickup.com/t/867838pj1
1. Add focus style
2. Improve accessibility
3. Fixed a bug where description was not clickable
4. Change copies
Full acessibility will need:
https://github.com/Frontify/web-app/pull/513
=> feat(AudioBlock): implement review findings

packages/shared/src/components/Attachments/Attachments.tsx, packages/shared/src/components/DownloadButton/DownloadButton.tsx
[see loom](https://www.loom.com/share/7572db0a2b1341f98a96290adf8473b5)
=> fix(shared): fix hover timing of attachment button

packages/dos-donts-block/src/DoDontItem.tsx
[Task](https://app.clickup.com/t/85ywx2ec0)
=> fix(DoAndDont): heading order accessibility

packages/image-block/src/settings.ts
As discussed with Schirmi and Luca, we will release the Image Block (Beta), without the link chooser and update the block as soon the new link chooser is available
=> feat(imageBlock): deactivate link

readme.md
Just updated the version numbers of pnpm and node
=> chore: readme update

examples/asset-upload/package.json, package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, pnpm-lock.yaml
=> chore: bump fondue

packages/thumbnail-grid-block/src/ThumbnailGridBlock.tsx
Fix for https://frontify.slack.com/archives/C04533CM2BU/p1689696811622299
=> fix(ThumbnailGrid): mass image upload not working

packages/dos-donts-block/src/DoDontItem.tsx
[Task](https://app.clickup.com/t/86782wz0f)
=> fix(DoDont): add missing aria-label

packages/dos-donts-block/src/DosDontsBlock.tsx
There were cases where the data was lost after entering.
=> fix(DoDontBlock): sometimes data is lost

examples/asset-upload/package.json, package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, pnpm-lock.yaml
bump fondue to 288, so this [task](https://app.clickup.com/t/86782wz0f) is finished
=> chore: fondue

packages/dos-donts-block/src/DoDontItem.tsx, packages/shared/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/FloatingLink.tsx
https://app.clickup.com/t/862k66rkr
=> feat(DoDont): insert modal is fixed

packages/dos-donts-block/src/DoDontItem.tsx
Will fix the discrepancy of the color in safari between view and edit mode
=> fix(DoDont): safari webkit-text-fill-color

packages/thumbnail-grid-block/src/ThumbnailGridBlock.spec.ct.tsx, packages/thumbnail-grid-block/src/ThumbnailGridBlock.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Image.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Item.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/RichTextEditors.tsx, packages/thumbnail-grid-block/src/types.ts
- Placeholder item has been removed, instead an actual empty item is added every time it's needed. (condition: last item is not empty)
- Uploading is happening in the child (Item.tsx) component instead of the parent (ThumbnailGridBlock.tsx) component. The child notifies the parent once the uploaded finishes and the appropriate handlers are called.
- Parent keeps track of the upload loading states of the children. Essentially to show the loading circle or not.
- It is possible to add several images at once.
=> feat(ThumbnailGridBlock): refactor storing

packages/template-block/src/TemplateBlock.tsx
This PR introduces a new approach for handling `openTemplateChooser` command events and fixes the stacking of an API calls for the template chooser `templateChosen` callback.
=> fix: openTemplateChooser dispatch/subscribe

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
=> chore: bump appBridge and cli

packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/UploadPlaceholder.tsx, packages/image-block/src/settings.ts
https://app.clickup.com/t/8678far4v
=> feat(ImageBlock): allow types other than images

packages/gradient-block/src/GradientBlock.spec.ct.tsx, packages/gradient-block/src/GradientBlock.tsx, packages/gradient-block/src/components/ColorTooltip.tsx, packages/gradient-block/src/components/SquareBadge.tsx, packages/gradient-block/src/components/SquareBadgesRow.tsx, packages/gradient-block/src/helpers/CssValueHelper.ts, packages/gradient-block/src/helpers/HexStringHelper.spec.ct.ts, packages/gradient-block/src/helpers/HexStringHelper.ts, packages/gradient-block/src/helpers/index.ts
1. Fix hex opacity not working in gradient stops. (https://app.clickup.com/t/2523021/TASK-9383)
2. Fix z-index issue when hovering color. (https://app.clickup.com/t/86939b2be)
=> fix(GradientBlock): opacity is not working

packages/template-block/src/TemplateBlock.tsx, packages/template-block/src/hooks/useTemplateBlockData.ts
I'm working on fixes for the Template Block layout issues.
This PR just moves the Template Block data handling into a custom hook, to make the code more legible and easier to bugfix/refactor
Fixes https://app.clickup.com/t/8693jhuuw
=> refactor: move template block data into hook [CU-8693jhuuw]

packages/asset-kit-block/src/AssetKitBlock.tsx, packages/asset-kit-block/src/components/InformationSection.tsx
[Task](https://app.clickup.com/t/2523021/TASK-9936)
=> fix: asset kit link chooser

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
as title states
https://app.clickup.com/t/8693nbz40
=> chore: bump @frontify/guideline-blocks-settings

packages/ui-pattern-block/src/UIPatternBlock.tsx, packages/ui-pattern-block/src/helpers/files.ts
https://app.clickup.com/t/8693u3n47
=> fix(CodeSandbox): block crashes

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/components/Image.tsx, packages/image-block/src/settings.ts, packages/image-block/src/types.ts
https://app.clickup.com/t/8693cyyce
=> feat(ImageBlock): add asset viewer security settings

packages/text-block/src/TextBlock.tsx
Avoid recreation of the text editor plugins on each render for a minor performance increase
=> perf: Stabilize text editor props

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/shared/src/components/ResponsiveImage/ResponsiveImage.spec.tsx, packages/shared/src/components/ResponsiveImage/ResponsiveImage.tsx
The default quality is 75 when omitted.
=> fix(ImageBlock): default quality was increased unintentionally

packages/quote-block/src/CustomIcon.tsx, packages/quote-block/src/QuoteBlock.tsx, packages/quote-block/src/QuoteBlockIcon.tsx, packages/quote-block/src/types.ts, packages/quote-block/src/utilities.tsx
Only request assets when custom icons are set in settings.
=> feat(QuoteBlock): reduce requests for assets

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
https://app.clickup.com/t/86945rfyz
=> chore: bump guideline-blocks-settings to 0.34.9

.github/workflows/continuous-integration.yml, package.json
lets pin the pnpm to 8 till we update that repo
=> ci: pin pnpm to 8

packages/template-block/src/TemplateBlock.tsx
Updates the `CreationForm` uri to consume the property passed from `app-bridge`
=> refactor(Templates): update uri to new reference

packages/image-block/src/ImageBlock.tsx
Wrapping the BlockItemWrapper in a useMemo heavily increased the performance, even though BlockItemWrapper is already memoized.
=> feat(ImageBlock): improve performance

packages/image-block/src/ImageBlock.tsx
Reverts Frontify/guideline-blocks#831
UseMemo is missing deps, and adding them eliminates all the performance improvements. Will need further investigation to improve performance.
=> Revert "feat(ImageBlock): improve performance"

.github/workflows/continuous-integration.yml, readme.md
Bonus also adjust readme.md with correct pnpm version
=> ci: use .nvmrc for node version

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/ImageBlock.tsx, packages/image-block/src/types.ts
Discussed with design that the correct new breakpoint is `sm` instead of `md`.
Most of the changes in `ImageBlock.tsx` are just whitespace changes. I added a wrapper div around.
=> feat(ImageBlock): update breakpoints to container breakpoints

packages/ui-pattern-block/src/UIPatternBlock.spec.ct.tsx, packages/ui-pattern-block/src/UIPatternBlock.tsx, packages/ui-pattern-block/src/components/Captions.tsx, packages/ui-pattern-block/src/helpers/files.ts, packages/ui-pattern-block/src/settings.ts, packages/ui-pattern-block/src/types.ts
https://app.clickup.com/t/8694mhxzg
=> feat(CodeSandboxBlock): add static support

packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/DosDontsBlock.spec.ct.tsx, packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/components/ImageComponent.tsx, packages/dos-donts-block/src/types.ts
https://app.clickup.com/t/2523021/TASK-11829
Add alt text to do&dont
=> feat(DoDontBlock): add alt field to images

packages/compare-slider-block/package.json, packages/compare-slider-block/src/CompareSliderBlock.spec.ct.tsx, packages/compare-slider-block/src/CompareSliderBlock.tsx, packages/compare-slider-block/src/components/EditorOverlay/EditorOverlay.tsx, packages/compare-slider-block/src/components/Label/Label.tsx, packages/compare-slider-block/src/components/SliderLine/SliderLine.tsx, packages/compare-slider-block/src/types.ts, pnpm-lock.yaml
https://app.clickup.com/t/2523021/TASK-11828
=> feat(CompareSlider): add alt text field

packages/thumbnail-grid-block/src/ThumbnailGridBlock.spec.ct.tsx, packages/thumbnail-grid-block/src/ThumbnailGridBlock.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Image.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Item.tsx
https://app.clickup.com/t/2523021/TASK-10618
=> feat(ThumbnailGridBlock): allow empty alt tags

packages/callout-block/src/CalloutBlock.spec.ct.tsx, packages/callout-block/src/CalloutBlock.tsx, packages/callout-block/src/components/CalloutIcon.tsx, packages/callout-block/src/components/CustomCalloutIcon.tsx
https://app.clickup.com/t/2523021/TASK-10771
Use callout type for alt for custom blocks.
=> feat(CalloutBlock): add descriptive alt to custom icons

packages/dos-donts-block/src/DosDontsBlock.tsx
Previously 2 requests were fired at the same time => race condition.
Merged them now into 1 request.
=> fix(DoDontBlock): initial color saving runs into race condition

package.json, packages/code-snippet-block/package.json, packages/shared/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
=> fix: update sandpack and codemirror

packages/compare-slider-block/package.json, packages/compare-slider-block/src/CompareSliderBlock.tsx, pnpm-lock.yaml
[TASK-12479](https://app.clickup.com/t/2523021/TASK-12479)
=> fix(CompareSlider): add grow so safari grows

packages/callout-block/src/components/CalloutIcon.tsx, packages/callout-block/src/components/icons/IconInfo.tsx, packages/callout-block/src/components/icons/IconLightbulb.tsx, packages/callout-block/src/components/icons/IconMegaphone.tsx, packages/callout-block/src/components/icons/index.ts, packages/callout-block/src/components/icons/type.ts
=> fix(Callout): accessibility icon

packages/callout-block/src/CalloutBlock.tsx, packages/callout-block/src/components/CalloutIcon.tsx, packages/callout-block/src/components/CustomCalloutIcon.tsx
Quote blocks: https://github.com/Frontify/guideline-blocks/pull/975
=> fix(CalloutBlock): unregister assets on switch off

packages/asset-kit-block/src/components/ThumbnailItem.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/Item.tsx, packages/thumbnail-grid-block/src/components/Thumbnail/RichTextEditors.tsx
=> fix(ThumbnailGrid): rte and small ux issues

packages/animation-curve-block/src/components/Card.tsx, packages/animation-curve-block/src/components/CardText.tsx
fix rte and small ui improivement
=> fix(AnimationCurve): rte and small ui improvement

packages/animation-curve-block/src/AnimationCurveBlock.tsx, packages/animation-curve-block/src/constants.ts
Implement container query based reflow for columns
Ticket: CU-86950mtu2
=> feat(AnimationCurveBlock): container query reflow

cypress/support/component-index.html, packages/dos-donts-block/package.json, packages/dos-donts-block/src/DosDontsBlock.spec.ct.tsx, packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/const.ts, packages/quote-block/manifest.json, pnpm-lock.yaml
=> feat(DnDBlock): implement column reflow based on container size

packages/template-block/src/TemplateBlock.tsx, packages/template-block/src/components/CtaButton.tsx, packages/template-block/src/hooks/useTemplateBlockData.ts, packages/template-block/src/types.ts, packages/template-block/tsconfig.json
=> feat(TemplateBlock): add container query based reflow for some elements

packages/template-block/src/hooks/useTemplateBlockData.ts
Ticket: CU-8697g1984
Before: 
After:
=> fix(TemplateBlock): button layout issue

postcss/scope.js
This way root css vars bundled within the block do not interfere with web app vars.
=> fix(PostCSS): scope root vars to block

packages/code-snippet-block/src/CodeSnippetBlock.tsx
https://app.clickup.com/t/2523021/TASK-13346
=> fix(CodeSnippet): announce copy to screen reader

packages/dos-donts-block/src/DosDontsBlock.tsx
=> fix(DnDBlock): button stacking on small sized containers

packages/thumbnail-grid-block/src/components/Thumbnail/RichTextEditors.tsx
Remove word-break style that was preventing the buttons to work properly
=> fix(ThumbnailGridBlock):  remove unnecessary css property

packages/image-block/src/components/Image.tsx
=> fix(ImageBlock): block is overflowing

pnpm-lock.yaml
renovate somehow fucked up the lockfile.
=> fix: broken lockfile

examples/asset-upload/package.json, package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/callout-block/package.json, packages/code-snippet-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/text-block/src/TextBlock.spec.ct.tsx, packages/text-block/src/TextBlock.tsx, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
Design requires a min height of 36px for the Text component.
=> feat(TextBlock): add a min height of 36px

packages/template-block/manifest.json
[CU-86984vn34](https://app.clickup.com/t/86984vn34)
=> fix(TemplateBlock): indexing

packages/quote-block/src/QuoteBlock.tsx
LBD: https://frontify.slack.com/archives/CCXT7AFD0/p1741703226405329
=> fix(Quote): author color should be body

packages/image-block/package.json, packages/image-block/src/components/ImageCaption.tsx, pnpm-lock.yaml
CU-8698ejnpb
----
Also removed 2 unused dependecies on that block:
- "@types/lodash-es"
- "@react-aria/focus"
=> fix(Image): spacing between image and title

packages/template-block/src/components/TemplatePreview.tsx, packages/template-block/src/hooks/useTemplateBlockData.ts, packages/template-block/src/settings.ts, packages/template-block/src/types.ts
=> fix(Template): color is nullable

packages/compare-slider-block/src/CompareSliderBlock.tsx, packages/compare-slider-block/src/settings.ts, packages/compare-slider-block/src/types.ts
=> fix: add a fallback value for default color object instead of null when clearing input

packages/template-block/src/components/TemplatePreview.tsx, packages/template-block/src/hooks/useTemplateBlockData.ts, packages/template-block/src/settings.ts, packages/template-block/src/types.ts
CU-8698f7y8z
too many colors in here, so missed the half of it :D
=> fix(Template): color can be null

packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/settings.ts, packages/dos-donts-block/src/types.ts
=> fix(DoDont): color can be null

packages/gradient-block/src/components/ColorTooltip.tsx, packages/gradient-block/src/components/EditAndDeleteColorBox.tsx, packages/gradient-block/src/types.ts
=> fix(GradientBlock): tooltip makes body overflow

packages/image-block/src/ImageBlock.tsx
* image title is automatically populated with the filename
=> fix(ImageBlock): Image title autofill

packages/asset-kit-block/src/components/AssetCount.tsx
The title and description have already been fixed, so I only had to adjust the alpha level with Tailwind
=> fix: adjusted the alpha level on the helper text

packages/asset-kit-block/src/AssetKitBlock.spec.ct.tsx, packages/asset-kit-block/src/AssetKitBlock.tsx
Hide AssetKitBlock in view mode when the title and description are missing
=> fix: hide AssetKitBlock in view mode if empty

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/callout-block/package.json, packages/callout-block/src/CalloutBlock.tsx, packages/code-snippet-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/figma-block/src/FigmaBlock.tsx, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/text-block/src/TextBlock.tsx, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, packages/ui-pattern-block/src/components/Captions.tsx, pnpm-lock.yaml
Will bump all blocks to use v4
=> feat(*): use app bridge v4

packages/asset-kit-block/src/components/ThumbnailItem.tsx
=> feat(AssetKit): use DAM alternative text if provided

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/animation-curve-block/src/AnimationCurveBlock.spec.ct.tsx, packages/animation-curve-block/src/components/BlankSlate.tsx, packages/animation-curve-block/src/components/Card.tsx, packages/animation-curve-block/src/components/CardText.tsx, packages/animation-curve-block/src/types.ts, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/callout-block/package.json, packages/code-snippet-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/image-block/src/components/DownloadAndAttachments.tsx, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
=> feat(Image): improved aria label for download button

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/components/Image.tsx, packages/image-block/src/components/helpers.spec.ts, packages/image-block/src/components/helpers.ts, packages/image-block/src/settings.ts, packages/image-block/src/types.ts
This PR contains:
* remove old alignment settings
* add new setting for autosizing and image alignment
=> feat(ImageBlock): add sidebar setting for autosizing
