Frontify/guideline-blocks

packages/block-settings/types/blocks/switch.ts, packages/sketchfab-block/src/settings.ts
Linked PR: https://github.com/Frontify/clarify/pull/10354
Since we now have multiple switch sizes, it would be useful to have the ability to control the size of the switch from the settings. This [Figma file](https://www.figma.com/file/SvZmrz3XSrRHqr8ZHHeunF/3D-Blocks?node-id=305%3A308418) is s demonstration of where we need switch sizes to be settable
=> feat: added switch size to type

packages/block-settings/types/index.ts, packages/callout-block/src/settings.ts, packages/figma-block/src/settings.ts, packages/quote-block/src/settings.ts, packages/sketchfab-block/src/settings.ts, packages/storybook-block/src/settings.ts
This PR renames all sections from "content" to "basics".
Ticket: https://app.clickup.com/t/2chb53h
=> chore(Settings): rename section from content to basics

packages/block-settings/types/blocks/colorInput.ts
This PR adjusts the colorInput type to still allow the legacy color format as value. This is needed for the fondue v11 update in clarify: https://github.com/Frontify/clarify/pull/10668
=> feat(BlockSettingsType): allow legacy color format for colorInput

packages/checklist-block/src/ChecklistBlock.tsx
Remove Fondue style import to prevent the issue below occuring on all block when a checklist is loaded:
https://user-images.githubusercontent.com/93908356/187639666-d86a6397-6995-42ea-b174-0fe46d62032c.mov
=> fix: remove fondue style from checklist block

packages/block-settings/types/blocks/checklist.ts
Allows function in `choices` with or without `Promise` return
```
{
id: 'test',
type: 'checklist',
choices: () =>
new Promise((resolve) => setTimeout(() => resolve([{ id: 'test-1', label: 'test 1' }]), 2000)),
},
```
=> feat: add function possibility for choices

packages/block-settings/types/blocks/base.ts
This PR adds a new type `Setting` to allow arrow functions on the `label`, `info` and `defaultValue` properties.
=> feat(BlockSettings): add new type Setting

packages/block-settings/types/blocks/linkChooser.ts
`label` is already declared inside the `BaseBlock` type, no need for it in the `LinkChooserBlock`.
=> fix(BlockSettings): remove label from LinkChooserBlock type

packages/color-kit-block/src/ColorKitBlock.tsx
We have an infinite loop when fetching all color palettes. Ideally we fix this in the app-bridge at some point, but for now memoization should do the job.
=> fix(ColorKitBlock): memoize palette ids

packages/color-kit-block/src/Color.tsx, packages/color-kit-block/src/ColorKitBlock.tsx, packages/color-kit-block/src/TooltipContent.spec.ct.tsx, packages/color-kit-block/src/TooltipContent.tsx, packages/color-kit-block/src/types.ts
Removing `:sm` helpers for now until we find a fix.
Also fix the color name in tooltip.
=> fix(ColorKitBlock): remove responsive styles

examples/asset-upload/package.json, package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/quote-block/src/QuoteBlock.tsx, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, pnpm-lock.yaml
- Update all packages to fondue beta 25
- Quote block: replace deprecated `actions` with `plugins` in RTE
=> chore: update fondue in all blocks/packages

packages/quote-block/src/QuoteBlock.tsx
Only save `content` instead of all settings.
Related PRs:
- https://github.com/Frontify/clarify/pull/12413
- https://github.com/Frontify/app-bridge/pull/262
=> feat(QuoteBlock): only save changed setting

packages/code-snippet-block/src/CodeSnippetBlock.tsx
- Use same font style & size as in old code snippet block
- Enable `control + A` to select all code in view mode
=> fix(CodeSnippetBlock): font style & enable `control + A` in view mode

examples/asset-upload/package.json, package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/code-snippet-block/src/CodeSnippetBlock.spec.ct.tsx, packages/code-snippet-block/src/CodeSnippetBlock.tsx, packages/color-block/package.json, packages/color-block/src/components/cards/CardsItem.spec.ct.tsx, packages/color-block/src/components/drops/DropsItem.spec.ct.tsx, packages/color-block/src/components/list/ListItem.spec.ct.tsx, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, packages/text-block/src/TextBlock.spec.ct.tsx, packages/text-block/src/TextBlock.tsx, packages/text-block/src/types.ts, pnpm-lock.yaml
Text block tests should pass after the gap prop is implemented within fondue: https://github.com/Frontify/fondue/pull/1184
Other tests need to be checked
=> chore: update fondue to beta72

packages/image-block/src/ImageBlock.spec.ct.tsx
View mode of block does not contain RTE, so the tests are failing.
=> fix(ImageBlock): test

packages/audio-block/src/AudioBlock.tsx, packages/audio-block/src/components/BlockAttachments.tsx, packages/audio-block/src/types.ts, packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/components/Image.tsx, packages/shared/src/components/Attachments/Attachments.spec.ct.tsx, packages/shared/src/components/Attachments/Attachments.tsx, packages/shared/src/components/Attachments/types.ts, packages/shared/src/components/DownloadButton/DownloadButton.spec.ct.tsx, packages/shared/src/components/DownloadButton/DownloadButton.tsx, packages/shared/src/components/DownloadButton/index.ts, packages/shared/src/components/DownloadButton/types.ts, packages/shared/src/components/index.ts
Splitting the downloadButton out of the attachments components so the attachments component has a single purpose.
There will be a follow-up PR with adjusting the Props of the attachment
=> feat(shared): split downloadButton out of the Attachment

packages/audio-block/src/components/BlockAttachments.tsx, packages/image-block/src/components/Image.tsx, packages/shared/src/components/Attachments/AttachmentItem.tsx, packages/shared/src/components/Attachments/Attachments.spec.ct.tsx, packages/shared/src/components/Attachments/Attachments.tsx, packages/shared/src/components/Attachments/types.ts
This is the follow up PR of https://github.com/Frontify/guideline-blocks/pull/501
It removes the term "attachment" from the Props of Attachment because its only purpose is handling attachments.
=> Feat(shared)/adjust attachment props

packages/asset-kit-block/src/settings.ts, packages/shared/src/settings/background.spec.ts, packages/shared/src/settings/background.ts, packages/shared/src/settings/borderRadius.ts, packages/shared/src/settings/defaultValues.ts, packages/shared/src/settings/index.ts
added `getBackgroundSettings` and used it within AssetKitBlock, and its also needed for the AnimationCurveBlock
Also extended the `getBorderRadiusSlider` so you can define a defaultRadius
=> feat(shared): add getBackgroundSettings

packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/settings.ts
-Checkbox in settings sidebar was not visible by default
-If H3 had margin top it broke the layout
=> fix(DoDontItem): margin top breaks the title

packages/image-block/src/components/Image.tsx, packages/shared/src/components/Attachments/Attachments.tsx, packages/shared/src/components/DownloadButton/DownloadButton.tsx, packages/shared/tailwind.config.js
1. `tw-outline-line` was not applied/generated. Added back the tailwind fondue tokens to the shared tailwind config.
2. When link was added to the image and the attachments were clicked the link opened. Prevented it by only wrapping the image itself inside <a> tags.
3. Tooltips were popping up immediately making it really annoying to click the options menu in the top-right. Added some delay.
4. Download button had a huge focus outline when clicked. Looked a bit ugly. Removed it when it is clicked. Still visible by tabbing.
=> fix(ImageBlock): fix various issues

packages/gradient-block/src/components/ColorFlyout.tsx
Just a small fix for this [bug](https://frontify.slack.com/archives/C02PSJTPA3D/p1683122013998859), as mentioned in the thread this version is already deployed to product.
=> fix(gradientBlock): remove dark:tw-bg-black-95

packages/asset-kit-block/src/AssetKitBlock.spec.ct.tsx, packages/asset-kit-block/src/AssetKitBlock.tsx, packages/asset-kit-block/src/components/AssetCount.tsx, packages/asset-kit-block/src/components/AssetGrid.tsx, packages/asset-kit-block/src/components/ThumbnailItem.tsx, packages/asset-kit-block/src/components/index.ts, packages/asset-kit-block/src/helpers/assetKitHelpers.ts, packages/asset-kit-block/src/settings.ts, packages/asset-kit-block/src/types.ts, packages/shared/src/components/RichTextEditor/SerializedText.tsx, packages/shared/src/components/RichTextEditor/serializer/serializeToHtml.ts
Ticket: https://app.clickup.com/t/8677vvdnn
=> feat(AssetKitBlock): changes & improvements

packages/callout-block/src/CalloutBlock.spec.ct.tsx, packages/callout-block/src/CalloutBlock.tsx
Paragraph text in Callout block get's overwritten by hub appearance css, this should fix it.
I also refactored the block a bit: removed the `style` tag for the css variables and directly added them to the element itself.
Last but not least: added a bunch of tests for all of the color handling.
Before:
After:
=> fix(CalloutBlock): prevent text color overwrite

packages/callout-block/src/CalloutBlock.spec.ct.tsx, packages/callout-block/src/CalloutBlock.tsx, packages/callout-block/src/helpers/getTextColor.ts, packages/shared/src/utilities/color/getReadableColor.spec.ts, packages/shared/src/utilities/color/getReadableColor.ts, packages/shared/src/utilities/color/index.ts
When a light color (white, lightblue etc.) is defined in the theme settings, the text color would be unreadable in the callout block with `appearance: light` (see issue mentioned [here](https://app.clickup.com/t/2523021/TASK-7595?comment=90100014900142&threadedComment=90100014912760) and/or loom [here](https://www.loom.com/share/ab1c45bb3f3b44d4822966a24ca57c78)).
This PR adds a new utility, which returns a darkened text color with a contrast ratio of at least 4.5 to the background. Also added some test for it.
=> feat(CalloutBlock): adjust for light colors

packages/asset-kit-block/src/AssetKitBlock.tsx
Reduce opacity when "download package" button is disabled (it's disabled when no assets are selected).
=> feat(AssetKitBlock): reduce opacity for disabled button

packages/callout-block/src/CalloutBlock.tsx, packages/shared/src/components/RichTextEditor/SerializedText.tsx
- Fix horizontal alignment of text, which wasn't working in view mode, because the content wasn't taking over 100% of the width
- Request from Martin: Remove margin of last text element inside the block, so that the content is also vertically centered inside the block
Before:
After:
=> fix(CalloutBlock): text alignment

packages/callout-block/src/helpers/getTextColor.ts
Adjust color logic, so that default colors in new guidelines are kept and not darkened.
Before:
After:
=> feat(CalloutBlock): adjust color logic

packages/code-snippet-block/src/CodeSnippetBlock.tsx
Adjust styling of default theme to match the one in the gradient block, see ticket: https://app.clickup.com/t/865c454z3
Before: 
After:
=> feat(CodeSnippetBlock): adjust default styling

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/components/Image.tsx, packages/image-block/src/components/helpers.ts
tickets: [image block general](https://app.clickup.com/t/86783gd9e) and [accessibility](https://app.clickup.com/t/86782x7u0)
* Attachment button same size as download button
* Buttons now always stays on top of image (despite it's padding or image size)
* Focusing order corrected
=> feat(ImageBlock): fix ux review

packages/shared/src/components/Attachments/Attachments.tsx
=> fix(shared): margin causes wrong outline

packages/shared/src/components/BlockItemWrapper/BlockItemWrapper.tsx, packages/shared/src/components/BlockItemWrapper/Toolbar.tsx
Previously the BlockItemWrapper toolbar overlapped the 100% of the width, so clicking the "Test description" was not possible, because the toolbar was on top of it.
I added pointer-events-none to the whole div, and added pointer-events-auto to the toolbar inside it, so only that part is clickable.
=> feat(shared): block item wrapper overlaps on top

packages/dos-donts-block/src/DoDontItem.tsx
On rerender the plugins got recreated which resulted in the text style dropdown closing.
=> fix(DoDontBlock): text dropdown closes

renovate.json
As it suggest to downgrade we should remove fondue from the renovate config, so it doesn't opens its downgrade PR's
=> chore: renovate fondue

examples/asset-upload/src/ExampleAssetUploadBlock.tsx, packages/asset-kit-block/src/components/AssetSelection.tsx, packages/asset-kit-block/src/components/ThumbnailItem.tsx, packages/audio-block/src/AudioBlock.tsx, packages/compare-slider-block/src/CompareSliderBlock.tsx, packages/dos-donts-block/src/DoDontItem.tsx, packages/dos-donts-block/src/DosDontsBlock.tsx, packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/Image.tsx, packages/thumbnail-grid-block/src/ThumbnailGridBlock.tsx
change all blocks that used deprecated function of the `AppBridge`, so the use the hooks as it should be
=> chore: appBridge deprecation notices

packages/asset-kit-block/src/AssetKitBlock.tsx, packages/asset-kit-block/tailwind.config.js
https://tailwindcss.com/docs/configuration#selector-strategy
New classes that are stronger:
=> fix(AssetKitBlock): tailwind styles were overriden

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, pnpm-lock.yaml
Basically just a bump.
- moved `@frontify/guideline-blocks-settings` within compare-slider-block from `devDependencies` to `dependencies`
- remove `@frontify/guideline-blocks-settings` from `shared` as its not used there
=> chore: bump @frontify/guideline-blocks-settings

examples/asset-upload/package.json, package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, pnpm-lock.yaml
Also bumped `fondue`, `babel/core` and `app-bridge`
=> chore: bump guideline-block-settings

packages/shared/package.json, pnpm-lock.yaml
Just noticed that for the shared the `eslint-config-typescript` was installed but within the `.eslintrc` the `eslint-config-react` was used so this should fix that
=> chore(shared): remove eslint-config-typescript package

packages/ui-pattern-block/src/settings.ts
Adjust the default value of `showSandboxLink` and `showResetButton` to `false`
[Task](https://app.clickup.com/t/8692ta8f9)
=> fix(UIPattern): settings default values

packages/audio-block/src/settings.ts, packages/callout-block/src/settings.ts, packages/compare-slider-block/src/settings.ts, packages/image-block/src/settings.ts, packages/quote-block/src/settings.tsx, packages/template-block/src/settings.ts
- The PR enables `showForTranslation` fields for all the blocks having Asset settings visible in the sidebar
- Settings enabled::
Block name | Enabled Setting 1 | Enabled Setting 2 | Enabled Setting 3
-- | -- | -- | --
Template | Template Input | Template Preview | Custom Preview
Image | Image (from asset input) | - | -
Callout | Icon Switch | - | -
Audio | Audio (from asset input) | - | -
Compare Slider | First Asset | Second Asset | -
Quote | Quotation Marks | - | -
=> chore: Show Asset setting fields in translated view

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/asset-kit-block/src/AssetKitBlock.tsx, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/shared/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
Update `app-bridge` in Asset kit block to use the new `api` signature for `generateBulkDownload` from `useAssetBulkDownload` hook
=> chore: bump app-bridge in asset-kit block

examples/asset-upload/package.json, packages/animation-curve-block/package.json, packages/asset-kit-block/package.json, packages/audio-block/package.json, packages/brand-positioning-block/package.json, packages/callout-block/package.json, packages/checklist-block/package.json, packages/code-snippet-block/package.json, packages/color-block/package.json, packages/color-kit-block/package.json, packages/color-scale-block/package.json, packages/compare-slider-block/package.json, packages/divider-block/package.json, packages/dos-donts-block/package.json, packages/example/package.json, packages/figma-block/package.json, packages/glyphs-block/package.json, packages/gradient-block/package.json, packages/image-block/package.json, packages/personal-note-block/package.json, packages/quote-block/package.json, packages/sketchfab-block/package.json, packages/storybook-block/package.json, packages/template-block/package.json, packages/text-block/package.json, packages/thumbnail-grid-block/package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
Bumping it in a single PR, so we can keep that noise out of this PR: https://github.com/Frontify/guideline-blocks/pull/699
=> chore: bump guideline-block-settings 0.29.16

packages/audio-block/src/settings.ts
Default positioning has been updated to reflect the positioning of the old audio block.
The title and description should be by default above the audio block, until the user changes this value.
=> fix: change default audio positioning

postcss/scope.js
1. The CSS scoping postCSS plugin regex was wrong. Tailwind classes like `bg-[rgb(150,150,150)]` were wrongly prepended because of the commas. Updated the regex with a negative lookahead, to not prepend with the selector if the comma is escaped. (tailwind transforms classes like that to `bg-[rgb(150\,150\,150)]`).
=> fix(*): css scoping regex is incorrect

packages/audio-block/src/AudioBlock.spec.ct.tsx, packages/audio-block/src/AudioBlock.tsx
- fixes the issue with not adding title if title is empty and a audio asset gets added
- adds tests to avoid regression
- replaces deprecated getBlockId function
[Task](https://app.clickup.com/t/8693jjk0q)
=> fix(AudioBlock): add title automatically if title is empty

packages/audio-block/src/AudioBlock.tsx
Use the `showSerializedText` property to hide the rich text editor on occasions when the block title or description is empty
=> fix(Audio Block):  remove empty text items

packages/dos-donts-block/src/DosDontsBlock.tsx, packages/dos-donts-block/src/index.ts
Include Fondue styles in bundle to fix tooltip arrow incorrect styling
=> fix (dosdonts-block): add fondue styles 

packages/template-block/src/components/TemplatePreview.tsx, packages/template-block/src/settings.ts
This PR fixes the settings regarding the image-align, see screenshot. When converting the `div` into a `button` in #728 / 79855f3bff540748b73083d064c3bc3458e82d2c, the button didn't automatically take up the full height & width, like the div.
How to test:
- Create a new template block
- Enable the preview
- Play around with the layouts, sizes, and alignment of the preview
- The image should be able to align within the image frame, and it should correctly be centered etc.
----
I also removed the "Left", "Center" & "Right" labels in the image anchor settings, as they were cut off (see screenshot above). They are now aligned with the same settings further up, so no label is shown (see screenshot below).
=> fix: Template Block Image Align

packages/template-block/src/settings.ts
Since most templates use 1 page only, and when first creating block it says "0 pages", we'll disable the page-count by default.
=> Template Block: Hide page count by default

packages/template-block/src/TemplateBlock.spec.ct.tsx, packages/template-block/src/TemplateBlock.tsx, packages/template-block/src/hooks/useTemplateBlockData.ts
Fixes https://app.clickup.com/t/8693qphk1
👁️  Template Block should be hidden for users that are not logged in, because they can't create publications anyway.
⚠️  Notice regarding tests: I decided to mock a user with ID `0`, which evaluates to `false` in my code. I know this is not ideal, but at least we can test the actual behavior this way. As soon as a better solution is in place we should be able to easily switch it out.
🧪  How to test:
- Create a guideline with this version of template block (local block development)
- In the powerbar, go to the "Share" menu and get the "Public Link" (e.g. `https://dev.frontify.test/d/G9HPcwB3gvuk`)
- Open the public link e.g. in an Inkognito tab (w/o authenticated user) - the guidelines should be shown, but not the template block
Issue:
=> feat(TemplateBlock): Use `getCurrentLoggedUser` to check if user is logged in [CU-8693qphk1]

packages/ui-pattern-block/src/UIPatternBlock.tsx, packages/ui-pattern-block/src/settings.ts
Removes the border radius setting from the sidebar when the border is switched off, as well as removing border radius styles in this same instance
=> fix: remove border radius when border is switched off

packages/image-block/src/components/Image.tsx
You can change a GIF's loop count using several tools, like https://ezgif.com/loop-count .
During our processing this is lost, and GIFs served via the frontify CDN loop infinitely. 
The image at the originURL still contains this property.
https://app.clickup.com/t/8693vp7d0
=> fix(ImageBlock): gif loop count is not respected

package.json, packages/ui-pattern-block/package.json, pnpm-lock.yaml
Override the nested `@codesandbox/sandpack-client` dependency of `@codesandbox/sandpack-react` at it's current version to fix the error reported in [this issue](https://github.com/codesandbox/sandpack/issues/1068) in the sandpack repository.
=> fix(ui-pattern-block): fix service-worker registration error

packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/ImageCaption.tsx
When an image is first uploaded the name and alt-text will be set to the uploaded image title, and to the filename if the title does not exist. When a second image is uploaded neither of these are updated
=> fix(Image-block): apply title when rte is empty

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/components/Image.tsx
This approach always requests images as wide as the container. This means smaller images for mobiles, and better support for the upcoming themes where container width might not always be 800 px.
=> feat(ImageBlock): remove 800px hardcoding

packages/template-block/src/TemplateBlock.spec.ct.tsx, packages/template-block/src/components/CtaButton.tsx, packages/template-block/src/settings.ts, packages/template-block/src/types.ts
This PR adds support to choose the CTA button styling between Primary, Secondary or Tertiary; before it was hardcoded to primary. Closes https://app.clickup.com/t/8693y5d2j
=> feat: Template block button styling [CU-8693y5d2j]

packages/template-block/src/TemplateBlock.tsx, packages/template-block/src/components/PreviewImage.tsx, packages/template-block/src/components/TemplatePreview.tsx, packages/template-block/src/components/types.ts, packages/template-block/src/hooks/useTemplateBlockData.ts
This PR reduces the amount of `/asset` API requests by only using the `useBlockAssets` hook once, instead of 3x. It also cleans up data handling, esp. regarding the `previewCustom`.
What to test: Set the preview to "Custom", and check that there actually is only 1 `/asset` API call. Before this PR, there should be 3 API calls.
Would be nice:
=> feat: Template Block Performance Improvements [CU-86940ffk3]

packages/asset-kit-block/src/AssetKitBlock.spec.ct.tsx, packages/asset-kit-block/src/AssetKitBlock.tsx, packages/asset-kit-block/src/types.ts
Previously the expiration and the url was set at the same time with different `setBlockSettings` which resulted in race condition.
Since the download expiration is extracted from the URL, I removed the `downloadExpiration` from the settings and now we only rely on the `downloadUrlBlock` to determine the expiration.
https://app.clickup.com/t/2523021/TASK-10645
=> feat(AssetKitBlock): remove race condition

packages/shared/src/components/ResponsiveImage/ResponsiveImage.tsx
After image processing some SVGs have null for `image.width` and `image.height`.
In these cases render them full width.
=> fix(ImageBlock): some svgs dont render

packages/asset-kit-block/src/AssetKitBlock.tsx, packages/asset-kit-block/src/helpers/assetKitHelpers.spec.ts, packages/asset-kit-block/src/helpers/assetKitHelpers.ts, packages/asset-kit-block/src/types.ts
With the new approach we need to calculate the expiration timestamp with the following formula:
CreationDate + Lifetime.
Previously it was:
Date.now() + Lifetime
=> fix(AssetKitBlock): created date is not taken into account

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/DownloadAndAttachments.tsx, packages/image-block/src/components/Image.tsx, packages/image-block/src/components/ImageCaption.tsx
https://www.figma.com/file/pYt8ECuB6Sc63cVtpKiDgf/Blocks---Updated?type=design&node-id=485-128059&mode=design&t=Ax3uS4Y06OpRKh6h-0
https://www.loom.com/share/911b7fb9330b4b9a8ac98dd2aae8a03f
CU-86947yy57
https://app.clickup.com/t/86947yy57
1. Attachments moved to parent component so overflow:hidden is not applied to that.
2. Added a 44px min height to the image component if there are attachments.
3. Hide captions if there is none in view mode.
=> feat(ImageBlock): allow attachments when block is empty

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/Image.tsx, packages/image-block/src/types.ts
Focus styles were hidden by the image wrapper due to an overflow:hidden style being applied. To fix this some refactoring was needed. This also adjusts the image functionality, as now the container of the image will always wrap to the image itself, meaning that if the image is not 100% of the width of the container and you apply a background, it will only be added to the area of padding around the image, instead of the full width, which is also shown in the Figma design to be the correct behaviour
=> fix: image focus styles

packages/image-block/src/ImageBlock.tsx
Relative positioning was missing from the image holder, so attachments were off on some layouts.
=> fix(ImageBlock): image attachments position is wrong

packages/template-block/src/settings.ts
Changes the `defaultValue` for the Template Block setting `Template editing` as well as fixes a typo in the label.
=> fix(TemplateBlock): update default value and label for template editing

packages/template-block/src/hooks/useTemplateBlockData.ts
When adding a template to the block that has a description, the text was visible in the textarea in edit mode, but was not applied to the block settings for view mode, unless the textarea was actioned in some way (e.g. focused).
Add the RTE converter to the `description` value `onTemplateSelected` as this triggers the `updateBlockSettings` method correctly. (THe method in `TemplateText` compares the values to update so without the converter it returns false and the two strings are the same on initial load.
1. navigate to a guideline and add a new template block
2. select a template that has a description that was set at the time pr `Publishing`
3. the description should render in the textarea in edit mode
4. switch to view mode and the description should render with the same value. …
=> fix(template-block): add rte converter to description

packages/image-block/src/ImageBlock.spec.ct.tsx, packages/image-block/src/components/Image.tsx, packages/shared/src/components/ResponsiveImage/ResponsiveImage.tsx, packages/shared/src/hooks/useImageContainer.tsx
If the image had borders applied, in some cases the image got blurred a bit. E.g. 1px border caused the container to shrink to 798px, while the image remained 800px wide. This very small discrepancy blurred the image. 
I experimented with different solutions.
1. If the border is applied, then remove that value from the requested image size. E.g. instead of 500, 600, 700, 800, request 498, 598, 698, 798. This worked, but on small screens the container is not always a multiple of 100, so it is possible to have a container of 580px wide, while requesting an image of 598px. This resulted in blurred images once again.
2. Always add 100px to the requested image size if there is border applied. This seems to be enough to always result crisp images. This PR implements this approach.
=> fix(ImageBlock): in some cases the image is not crisp

packages/thumbnail-grid-block/src/components/Grid/Grid.tsx
New breakpoints are set according to this chart:
And this loom:
https://www.loom.com/share/f6b6fa5599d94e5282ba3ec4c2c29e16
CU:
https://app.clickup.com/t/8694ky6tc
=> fix(ThumbnailGridBlock): breakpoints are not set correctly

packages/animation-curve-block/manifest.json, packages/dos-donts-block/manifest.json, packages/thumbnail-grid-block/manifest.json
Update the `manifest.json`, so the block content that is stored as arrays is indexable via `searchFields` too.
CU-8694mc5vj
=> feat(*): make content in arrays searchable

packages/callout-block/src/CalloutBlock.spec.ct.tsx, packages/callout-block/src/CalloutBlock.tsx
[From MDN docs:](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type)
`Size containment turns off the ability of an element to get size information from its contents, which is important for container queries to avoid infinite loops.`
Meaning with container queries it is not possible to get the width of the content inside, so hugging the content width is not possible.
=> fix(CalloutBlock): hug contents is collapsing

postcss/scope.js
Only extend the scoping to modals if the selector contains a class.
This way selectors like `*` `:before` `h1` will not be added to modals and overlays which previously overrode things.
=> fix(PostCSS): only scope classes

postcss/scope.js
With the new fondue components there are a lot of conflicts in CSS, so removing it from blocks scoping.
=> fix(CSS): remove radix overlays from CSS scoping

packages/figma-block/src/FigmaBlock.tsx, packages/figma-block/src/FigmaEmptyBlock.tsx
Move `<FigmaEmptyBlock />` to a new component. Otherwise the click handler was never called on the button.
I suspect due to it being recreated on every rerender and the mousedown => mouseup was happening on two different components.
=> fix(FigmaBlock): asset chooser does not open

postcss/scope.js
Otherwise classes like `_root-4kx7u` in modals are not applied.
=> fix(PostCSS): only scope tailwind classes

postcss/scope.js
The fix applied in https://github.com/Frontify/guideline-blocks/pull/940 was not working as the classes start with `.tw` not `tw` 🤦 
Changed the approach so now classes like `group-hover:tw-bg-red-40` are also applied.
Fixes
https://app.clickup.com/t/2523021/TASK-12450
=> fix(CSS): scoping is not applied

packages/dos-donts-block/src/DoDontItem.tsx, postcss/scope.js
Issue found during testing:
- background color of block (removed)
- overlapping outline of the blockItemWrapper (offset to 0)
Also replaced deprecated `getBlockId()`
Also found an issue with the scoping around tooltips, as the class was prefixed but lived on the root. 
So now we only prefix tailwind classes and tags and no other classes this fixes the issue bolding without introducing new issues. 
https://app.clickup.com/t/2523021/TASK-13279
=> fix(DoDont): overlapping and background color

packages/quote-block/src/QuoteBlock.tsx
Ticket: CU-8697g24cc
Before:
After:
=> fix(QuoteBlock): prevent text from overflowing outside container

packages/audio-block/src/AudioBlock.tsx, packages/audio-block/src/components/AudioPlayer.tsx, packages/audio-block/src/settings.ts
After discussion of it, this is useless on Audio Block and only needed for video. 
For Audio we need transscript which is a different concept, and needs to be checked on how we gonna implement it.
=> refactor(Audio): remove CC

packages/image-block/src/ImageBlock.tsx, packages/image-block/src/components/DownloadAndAttachments.tsx, packages/image-block/src/helpers/isImageDownloadable.spec.ts, packages/image-block/src/helpers/isImageDownloadable.ts
TASK-14053
----
Basic Handling for the 2 cases
For Download through the block we need to know if the asset is protected (basically what the helper: `isImageDownloadable` does)
For opening the asset viewer, the asset viewer only needs to know about the options of the block or guideline if the asset is downloadable and then cares on its own if the asset is protected.
CC: @urietberger 
----
This pull request involves several changes to the `ImageBlock` component and its related files to improve the handling of downloadable images. The key changes include updating the import statements, renaming variables for clarity, and refactoring the `isImageDownloadable` function and its tests.
* [`packages/image-block/src/ImageBlock.tsx`](diffhunk://#diff-17309e5c0933869ae6e1db21f3368d5a6a621335506c53ecc …
=> fix(Image): improve handling for asset viewer

packages/compare-slider-block/src/CompareSliderBlock.tsx, packages/compare-slider-block/src/components/SliderLine/SliderLine.tsx
bit of a workaround because the original button that is focused is inside the 3rd party package and not customisable.
=> fix(CompareSliderBlock): add focus ring to handle
